---
- hosts: servers
  gather_facts: yes
  become: yes
  become_user: root

  tasks:
    - name: Ensure logrotate is installed.
      ansible.builtin.apt:
        name: logrotate
        state: present
        update_cache: yes

    - name: Configure custom log rotation.
      ansible.builtin.copy:
        dest: /etc/logrotate.d/local-custom
        owner: root
        group: root
        mode: '0644'
        content: |
          /var/log/local-custom/*.log {
              weekly
              rotate 1
              missingok
              notifempty
              compress
              delaycompress
              copytruncate
          }

    - name: Perform a dist-upgrade.
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes

    - name: Check if a reboot is required.
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: no
      register: reboot_required_file

    - name: Reboot the server (if required).
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists == true

    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: yes
